// Generated by gencpp from file sandbox/mipper.msg
// DO NOT EDIT!


#ifndef SANDBOX_MESSAGE_MIPPER_H
#define SANDBOX_MESSAGE_MIPPER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sandbox
{
template <class ContainerAllocator>
struct mipper_
{
  typedef mipper_<ContainerAllocator> Type;

  mipper_()
    : label()
    , data()  {
    }
  mipper_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sandbox::mipper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sandbox::mipper_<ContainerAllocator> const> ConstPtr;

}; // struct mipper_

typedef ::sandbox::mipper_<std::allocator<void> > mipper;

typedef boost::shared_ptr< ::sandbox::mipper > mipperPtr;
typedef boost::shared_ptr< ::sandbox::mipper const> mipperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sandbox::mipper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sandbox::mipper_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sandbox

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sandbox': ['/home/tomvillegasm/duckietown-uoct/catkin_ws/src/sandbox/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::mipper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::mipper_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::mipper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::mipper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::mipper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::mipper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sandbox::mipper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03274f755f3fa14034497c515fc2e37a";
  }

  static const char* value(const ::sandbox::mipper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03274f755f3fa140ULL;
  static const uint64_t static_value2 = 0x34497c515fc2e37aULL;
};

template<class ContainerAllocator>
struct DataType< ::sandbox::mipper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sandbox/mipper";
  }

  static const char* value(const ::sandbox::mipper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sandbox::mipper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
"int16[] data\n"
;
  }

  static const char* value(const ::sandbox::mipper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sandbox::mipper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mipper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sandbox::mipper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sandbox::mipper_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SANDBOX_MESSAGE_MIPPER_H
