// Generated by gencpp from file sandbox/MultiArraySubDimension.msg
// DO NOT EDIT!


#ifndef SANDBOX_MESSAGE_MULTIARRAYSUBDIMENSION_H
#define SANDBOX_MESSAGE_MULTIARRAYSUBDIMENSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sandbox
{
template <class ContainerAllocator>
struct MultiArraySubDimension_
{
  typedef MultiArraySubDimension_<ContainerAllocator> Type;

  MultiArraySubDimension_()
    : label()
    , colors()  {
    }
  MultiArraySubDimension_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , colors(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _colors_type;
  _colors_type colors;





  typedef boost::shared_ptr< ::sandbox::MultiArraySubDimension_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sandbox::MultiArraySubDimension_<ContainerAllocator> const> ConstPtr;

}; // struct MultiArraySubDimension_

typedef ::sandbox::MultiArraySubDimension_<std::allocator<void> > MultiArraySubDimension;

typedef boost::shared_ptr< ::sandbox::MultiArraySubDimension > MultiArraySubDimensionPtr;
typedef boost::shared_ptr< ::sandbox::MultiArraySubDimension const> MultiArraySubDimensionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sandbox::MultiArraySubDimension_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sandbox

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sandbox': ['/home/tomvillegasm/duckietown-uoct/catkin_ws/src/sandbox/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::MultiArraySubDimension_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::MultiArraySubDimension_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::MultiArraySubDimension_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6def1837502a9057eabbae76543b5b87";
  }

  static const char* value(const ::sandbox::MultiArraySubDimension_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6def1837502a9057ULL;
  static const uint64_t static_value2 = 0xeabbae76543b5b87ULL;
};

template<class ContainerAllocator>
struct DataType< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sandbox/MultiArraySubDimension";
  }

  static const char* value(const ::sandbox::MultiArraySubDimension_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label # cross, street, blink warning\n"
"int16[] colors # [red,gree,blue,custom]\n"
;
  }

  static const char* value(const ::sandbox::MultiArraySubDimension_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.colors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiArraySubDimension_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sandbox::MultiArraySubDimension_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sandbox::MultiArraySubDimension_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "colors[]" << std::endl;
    for (size_t i = 0; i < v.colors.size(); ++i)
    {
      s << indent << "  colors[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.colors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SANDBOX_MESSAGE_MULTIARRAYSUBDIMENSION_H
