// Generated by gencpp from file sandbox/TimeMultiArray.msg
// DO NOT EDIT!


#ifndef SANDBOX_MESSAGE_TIMEMULTIARRAY_H
#define SANDBOX_MESSAGE_TIMEMULTIARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sandbox
{
template <class ContainerAllocator>
struct TimeMultiArray_
{
  typedef TimeMultiArray_<ContainerAllocator> Type;

  TimeMultiArray_()
    : StoplightTime()
    , minutes()
    , seconds()  {
    }
  TimeMultiArray_(const ContainerAllocator& _alloc)
    : StoplightTime(_alloc)
    , minutes(_alloc)
    , seconds(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _StoplightTime_type;
  _StoplightTime_type StoplightTime;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _minutes_type;
  _minutes_type minutes;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _seconds_type;
  _seconds_type seconds;





  typedef boost::shared_ptr< ::sandbox::TimeMultiArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sandbox::TimeMultiArray_<ContainerAllocator> const> ConstPtr;

}; // struct TimeMultiArray_

typedef ::sandbox::TimeMultiArray_<std::allocator<void> > TimeMultiArray;

typedef boost::shared_ptr< ::sandbox::TimeMultiArray > TimeMultiArrayPtr;
typedef boost::shared_ptr< ::sandbox::TimeMultiArray const> TimeMultiArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sandbox::TimeMultiArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sandbox::TimeMultiArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sandbox

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sandbox': ['/home/tomvillegasm/duckietown-uoct/catkin_ws/src/sandbox/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::TimeMultiArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::TimeMultiArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::TimeMultiArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::TimeMultiArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::TimeMultiArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::TimeMultiArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sandbox::TimeMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f037166f662f8756df277bb1c73f274";
  }

  static const char* value(const ::sandbox::TimeMultiArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f037166f662f875ULL;
  static const uint64_t static_value2 = 0x6df277bb1c73f274ULL;
};

template<class ContainerAllocator>
struct DataType< ::sandbox::TimeMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sandbox/TimeMultiArray";
  }

  static const char* value(const ::sandbox::TimeMultiArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sandbox::TimeMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header StoplightTime\n"
"int16[] minutes\n"
"int16[] seconds\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sandbox::TimeMultiArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sandbox::TimeMultiArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.StoplightTime);
      stream.next(m.minutes);
      stream.next(m.seconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeMultiArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sandbox::TimeMultiArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sandbox::TimeMultiArray_<ContainerAllocator>& v)
  {
    s << indent << "StoplightTime: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.StoplightTime);
    s << indent << "minutes[]" << std::endl;
    for (size_t i = 0; i < v.minutes.size(); ++i)
    {
      s << indent << "  minutes[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.minutes[i]);
    }
    s << indent << "seconds[]" << std::endl;
    for (size_t i = 0; i < v.seconds.size(); ++i)
    {
      s << indent << "  seconds[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.seconds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SANDBOX_MESSAGE_TIMEMULTIARRAY_H
