// Generated by gencpp from file sandbox/Stoplight.msg
// DO NOT EDIT!


#ifndef SANDBOX_MESSAGE_STOPLIGHT_H
#define SANDBOX_MESSAGE_STOPLIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sandbox
{
template <class ContainerAllocator>
struct Stoplight_
{
  typedef Stoplight_<ContainerAllocator> Type;

  Stoplight_()
    : Stoplight()
    , type()
    , direction()
    , colors()  {
    }
  Stoplight_(const ContainerAllocator& _alloc)
    : Stoplight(_alloc)
    , type(_alloc)
    , direction(_alloc)
    , colors(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Stoplight_type;
  _Stoplight_type Stoplight;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _colors_type;
  _colors_type colors;





  typedef boost::shared_ptr< ::sandbox::Stoplight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sandbox::Stoplight_<ContainerAllocator> const> ConstPtr;

}; // struct Stoplight_

typedef ::sandbox::Stoplight_<std::allocator<void> > Stoplight;

typedef boost::shared_ptr< ::sandbox::Stoplight > StoplightPtr;
typedef boost::shared_ptr< ::sandbox::Stoplight const> StoplightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sandbox::Stoplight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sandbox::Stoplight_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sandbox

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sandbox': ['/home/tomvillegasm/duckietown-uoct/catkin_ws/src/sandbox/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::Stoplight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sandbox::Stoplight_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::Stoplight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandbox::Stoplight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::Stoplight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandbox::Stoplight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sandbox::Stoplight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6654bda664e47f8222314d4f89a55a15";
  }

  static const char* value(const ::sandbox::Stoplight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6654bda664e47f82ULL;
  static const uint64_t static_value2 = 0x22314d4f89a55a15ULL;
};

template<class ContainerAllocator>
struct DataType< ::sandbox::Stoplight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sandbox/Stoplight";
  }

  static const char* value(const ::sandbox::Stoplight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sandbox::Stoplight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Stoplight\n"
"string type # cross, street, blink warning\n"
"string direction # norht2south, east2west, up2down\n"
"int16[] colors # [red,gree,blue,custom]\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sandbox::Stoplight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sandbox::Stoplight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Stoplight);
      stream.next(m.type);
      stream.next(m.direction);
      stream.next(m.colors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stoplight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sandbox::Stoplight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sandbox::Stoplight_<ContainerAllocator>& v)
  {
    s << indent << "Stoplight: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Stoplight);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
    s << indent << "colors[]" << std::endl;
    for (size_t i = 0; i < v.colors.size(); ++i)
    {
      s << indent << "  colors[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.colors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SANDBOX_MESSAGE_STOPLIGHT_H
